#WEB SERVICE RSEM LIMMA50

library("RCurl")
library("rjson")

# Accept SSL certificates issued by public Certificate Authorities
options(RCurlOptions = list(cainfo = system.file("CurlSSL", "cacert.pem", package = "RCurl")))

h = basicTextGatherer()
hdr = basicHeaderGatherer()

req =  list(
  Inputs = list(
    "input1"= list(
      list(
        'expert_PAM50_subtypes' = "",
        'ABAT' = sample$ABAT,
        'ACADSB' = sample$ACADSB,
        'AGR2' = sample$AGR2,
        'AGR3' = sample$AGR3,
        'ALX4' = sample$ALX4,
        'AQP1' = sample$AQP1,
        'AR' = sample$AR,
        'ART3' = sample$ART3,
        'ASB13' = sample$ASB13,
        'ATP13A5' = sample$ATP13A5,
        'AURKA' = sample$AURKA,
        'AURKB' = sample$AURKB,
        'BCAS1' = sample$BCAS1,
        'BCL11A' = sample$BCL11A,
        'BCL2' = sample$BCL2,
        'BIRC5' = sample$BIRC5,
        'BOC' = sample$BOC,
        'BUB1' = sample$BUB1,
        'BUB1B' = sample$BUB1B,
        'C2CD4B' = sample$C2CD4B,
        'C2orf40' = sample$C2orf40,
        'C2orf88' = sample$C2orf88,
        'C5AR2' = sample$C5AR2,
        'C6orf211' = sample$C6orf211,
        'C9orf152' = sample$C9orf152,
        'C9orf170' = sample$C9orf170,
        'CA12' = sample$CA12,
        'CAPN11' = sample$CAPN11,
        'CAPN13' = sample$CAPN13,
        'CAV2' = sample$CAV2,
        'CBR3' = sample$CBR3,
        'CBX7' = sample$CBX7,
        'CCDC170' = sample$CCDC170,
        'CCNA2' = sample$CCNA2,
        'CCNB1' = sample$CCNB1,
        'CCNB2' = sample$CCNB2,
        'CDC20' = sample$CDC20,
        'CDC25A' = sample$CDC25A,
        'CDC25C' = sample$CDC25C,
        'CDCA3' = sample$CDCA3,
        'CDCA8' = sample$CDCA8,
        'CENPA' = sample$CENPA,
        'CENPL' = sample$CENPL,
        'CENPN' = sample$CENPN,
        'CEP55' = sample$CEP55,
        'CGB7' = sample$CGB7,
        'CHODL' = sample$CHODL,
        'CLCA2' = sample$CLCA2,
        'CLCA4' = sample$CLCA4,
        'CLCN4' = sample$CLCN4,
        'CLDN19' = sample$CLDN19,
        'CLSTN2' = sample$CLSTN2,
        'CMA1' = sample$CMA1,
        'CMBL' = sample$CMBL,
        'CNTNAP3' = sample$CNTNAP3,
        'CT62' = sample$CT62,
        'CX3CL1' = sample$CX3CL1,
        'CXCL3' = sample$CXCL3,
        'CYP2B7P' = sample$CYP2B7P,
        'CYP4Z2P' = sample$CYP4Z2P,
        'DBNDD2' = sample$DBNDD2,
        'DEGS2' = sample$DEGS2,
        'DEPDC1B' = sample$DEPDC1B,
        'DLK2' = sample$DLK2,
        'DMD' = sample$DMD,
        'DMRTC2' = sample$DMRTC2,
        'DRAIC' = sample$DRAIC,
        'DSN1' = sample$DSN1,
        'DUSP7' = sample$DUSP7,
        'EDN3' = sample$EDN3,
        'ELOVL2' = sample$ELOVL2,
        'EOGT' = sample$EOGT,
        'EPHA2' = sample$EPHA2,
        'EPHB1' = sample$EPHB1,
        'EPS15L1' = sample$EPS15L1,
        'ERBB2' = sample$ERBB2,
        'ERBB4' = sample$ERBB4,
        'ERGIC1' = sample$ERGIC1,
        'ESPL1' = sample$ESPL1,
        'ESR1' = sample$ESR1,
        'EXO1' = sample$EXO1,
        'EZH1' = sample$EZH1,
        'FAM110D' = sample$FAM110D,
        'FAM171A1' = sample$FAM171A1,
        'FAM196B' = sample$FAM196B,
        'FAM19A3' = sample$FAM19A3,
        'FAM64A' = sample$FAM64A,
        'FAM72B' = sample$FAM72B,
        'FAM72D' = sample$FAM72D,
        'FAM83D' = sample$FAM83D,
        'FANCA' = sample$FANCA,
        'FAT2' = sample$FAT2,
        'FBP1' = sample$FBP1,
        'FGD3' = sample$FGD3,
        'FGF2' = sample$FGF2,
        'FGFR2' = sample$FGFR2,
        'FOXA1' = sample$FOXA1,
        'FOXC1' = sample$FOXC1,
        'FOXM1' = sample$FOXM1,
        'FUT3' = sample$FUT3,
        'FXYD1' = sample$FXYD1,
        'FZD9' = sample$FZD9,
        'G6PD' = sample$G6PD,
        'GABRP' = sample$GABRP,
        'GALNT7' = sample$GALNT7,
        'GATA3' = sample$GATA3,
        'GATA3-AS1' = sample$GATA3.AS1,
        'GDF5' = sample$GDF5,
        'GFAP' = sample$GFAP,
        'GFRA1' = sample$GFRA1,
        'GGCT' = sample$GGCT,
        'GINS1' = sample$GINS1,
        'GINS2' = sample$GINS2,
        'GLI1' = sample$GLI1,
        'GPM6B' = sample$GPM6B,
        'GPR144' = sample$GPR144,
        'GPR160' = sample$GPR160,
        'GRB7' = sample$GRB7,
        'GREB1' = sample$GREB1,
        'GRIA4' = sample$GRIA1,
        'GSG2' = sample$GSG2,
        'GSN' = sample$GSN,
        'HID1' = sample$HID1,
        'HJURP' = sample$HJURP,
        'HORMAD1' = sample$HORMAD1,
        'HOXA2' = sample$HOXA2,
        'HPSE2' = sample$HPSE2,
        'IFFO2' = sample$IFFO2,
        'IFRD1' = sample$IFRD1,
        'IGF1R' = sample$IGF1R,
        'IL17B' = sample$IL17B,
        'INPP4B' = sample$INPP4B,
        'IQGAP3' = sample$IQGAP3,
        'KCNJ11' = sample$KCNJ11,
        'KCNMB1' = sample$KCNMB1,
        'KCNQ4' = sample$KCNQ4,
        'KIF18B' = sample$KIF18B,
        'KIF20A' = sample$KIF20A,
        'KIF2C' = sample$KIF2C,
        'KIFC1' = sample$KIFC1,
        'KLHL29' = sample$KLHL29,
        'KRT16' = sample$KRT16,
        'KY' = sample$KY,
        'LEMD1' = sample$LEMD1,
        'LINC00173' = sample$LINC00173,
        'LINC00472' = sample$LINC00472,
        'LINC01105' = sample$LINC01105,
        'LRRC3B' = sample$LRRC3B,
        'MAG' = sample$MAG,
        'MBOAT1' = sample$MBOAT1,
        'MCM10' = sample$MCM10,
        'MELK' = sample$MELK,
        'MIA' = sample$MIA,
        'MICALL1' = sample$MICALL1,
        'MIEN1' = sample$MIEN1,
        'MIR143HG' = sample$MIR143HG,
        'MLPH' = sample$MLPH,
        'MMRN2' = sample$MMRN2,
        'MPHOSPH6' = sample$MPHOSPH6,
        'MRGPRX3' = sample$MRGPRX3,
        'MYBL2' = sample$MYBL2,
        'NAGS' = sample$NAGS,
        'NAT1' = sample$NAT1,
        'NCAPG' = sample$NCAPG,
        'NCAPH' = sample$NCAPH,
        'NDC80' = sample$NDC80,
        'NDRG2' = sample$NDRG2,
        'NEFL' = sample$NEFL,
        'NEK10' = sample$NEK10,
        'NEK2' = sample$NEK2,
        'NPM2' = sample$NPM2,
        'NPY1R' = sample$NPY1R,
        'NRG2' = sample$NRG2,
        'NTF4' = sample$NTF4,
        'NTRK2' = sample$NTRK2,
        'NUDT8' = sample$NUDT8,
        'NUF2' = sample$NUF2,
        'NUSAP1' = sample$NUSAP1,
        'NXNL2' = sample$NXNL2,
        'OR2L13' = sample$OR2L13,
        'ORC6' = sample$ORC6,
        'OSR1' = sample$OSR1,
        'OVCH2' = sample$OVCH2,
        'PADI2' = sample$PADI2,
        'PAK7' = sample$PAK7,
        'PAMR1' = sample$PAMR1,
        'PARD6B' = sample$PARD6B,
        'PCSK6' = sample$PCSK6,
        'PGAP3' = sample$PGAP3,
        'PGR' = sample$PGR,
        'PLK1' = sample$PLK1,
        'PMAIP1' = sample$PMAIP1,
        'POLQ' = sample$POLQ,
        'PPM1F' = sample$PPM1F,
        'PPP1R14C' = sample$PPP1R14C,
        'PRC1' = sample$PRC1,
        'PRNP' = sample$PRNP,
        'PRR15' = sample$PRR15,
        'PTGER3' = sample$PTGER3,
        'PTPRZ1' = sample$PTPRZ1,
        'RACGAP1' = sample$RACGAP1,
        'RASGEF1C' = sample$RASGEF1C,
        'RBM24' = sample$RBM24,
        'RERG' = sample$RERG,
        'RGMA' = sample$RGMA,
        'RGS22' = sample$RGS22,
        'RHOB' = sample$RHOB,
        'RIMS4' = sample$RIMS4,
        'RLN2' = sample$RLN2,
        'RNF186' = sample$RNF186,
        'ROPN1' = sample$ROPN1,
        'ROPN1B' = sample$ROPN1B,
        'RRM2' = sample$RRM2,
        'SCN2B' = sample$SCN2B,
        'SCN3B' = sample$SCN3B,
        'SCRG1' = sample$SCRG1,
        'SCUBE2' = sample$SCUBE2,
        'SDPR' = sample$SDPR,
        'SEC16A' = sample$SEC16A,
        'SFRP1' = sample$SFRP1,
        'SFT2D2' = sample$SFT2D2,
        'SGK3' = sample$SGK3,
        'SGOL1' = sample$SGOL1,
        'SHCBP1' = sample$SHCBP1,
        'SIDT1' = sample$SIDT1,
        'SKA1' = sample$SKA1,
        'SLC22A11' = sample$SLC22A11,
        'SLC39A6' = sample$SLC39A6,
        'SLC44A4' = sample$SLC44A4,
        'SLC7A3' = sample$SLC7A3,
        'SLC7A8' = sample$SLC7A8,
        'SMYD1' = sample$SMYD1,
        'SOX10' = sample$SOX10,
        'SOX17' = sample$SOX17,
        'SPAG5' = sample$SPAG5,
        'SPARCL1' = sample$SPARCL1,
        'SPDEF' = sample$SPDEF,
        'SPRY2' = sample$SPRY2,
        'SRSF12' = sample$SRSF12,
        'STAC2' = sample$STAC2,
        'STARD3' = sample$STARD3,
        'STC2' = sample$STC2,
        'SUSD3' = sample$SUSD3,
        'SYNM' = sample$SYNM,
        'TAC1' = sample$TAC1,
        'TBC1D9' = sample$TBC1D9,
        'TBX19' = sample$TBX19,
        'TEPP' = sample$TEPP,
        'TFCP2L1' = sample$TFCP2L1,
        'TFF1' = sample$TFF1,
        'TFF3' = sample$TFF3,
        'THSD4' = sample$THSD4,
        'TICRR' = sample$TICRR,
        'TINAGL1' = sample$TINAGL1,
        'TMEM220' = sample$TMEM220,
        'TMEM45B' = sample$TMEM45B,
        'TMEM86A' = sample$TMEM86A,
        'TPRG1' = sample$TPRG1,
        'TPX2' = sample$TPX2,
        'TRIM29' = sample$TRIM29,
        'TROAP' = sample$TROAP,
        'TRPM3' = sample$TRPM3,
        'TRPM6' = sample$TRPM6,
        'TRPV6' = sample$TRPV6,
        'TSLP' = sample$TSLP,
        'TSPAN1' = sample$TSPAN1,
        'TTK' = sample$TTK,
        'UBE2C' = sample$UBE2C,
        'UBE2T' = sample$UBE2T,
        'VGLL1' = sample$VGLL1,
        'VPS37B' = sample$VPS37B,
        'WDR19' = sample$WDR19,
        'WIF1' = sample$WIF1,
        'WWP1' = sample$WWP1,
        'XBP1' = sample$XBP1,
        'ZNF516' = sample$ZNF516,
        'ZNF552' = sample$ZNF552
      )
    )
  ),
  GlobalParameters = setNames(fromJSON('{}'), character(0))
)

body = enc2utf8(toJSON(req))
api_key = "J/SE8pjoaMFdqmAsw9R0ANNbLHKmSn2fS4fp8aWU0jqYtJdUuAT5fegTxpEbvUuSAkN+TjmsbO2Si4Z1PSCBVQ==" #  API key for the web service RSEM limma50
authz_hdr = paste('Bearer', api_key, sep=' ')

h$reset()
curlPerform(url = "https://ussouthcentral.services.azureml.net/workspaces/e5a11d5543d74f648ea577561c656273/services/f62b903eb7a5438f9521655059f5633d/execute?api-version=2.0&format=swagger",
            httpheader=c('Content-Type' = "application/json", 'Authorization' = authz_hdr),
            postfields=body,
            writefunction = h$update,
            headerfunction = hdr$update,
            verbose = TRUE
)

headers = hdr$value()
httpStatus = headers["status"]
if (httpStatus >= 400)
{
  print(paste("The request failed with status code:", httpStatus, sep=" "))
  
  # Print the headers - they include the requert ID and the timestamp, which are useful for debugging the failure
  print(headers)
}

print("Result:")
result = h$value()
print(fromJSON(result))


